name: Chamomile
version: 1.0.1
main: fun.blue_millennium.Main
description: Encoded by Blue Millennium
authors: [ SukaXD, Suisuroru ]

commands:
  kill:
    description: kill entities
    usage: /kill <entities>
  ban:
    description: Ban a player
    usage: /ban <player> <reason>
  pardon:
    description: Unban a player
    usage: /pardon <player>
  chamomilehelp:
    description: Chamomile help
    usage: /chamomilehelp
    aliases: [ cmhelp ]
  report:
    description: Report a player
    usage: /report <player> <reason>
    aliases: [ cmrp ]
  cmreload:
    description: Reload config
    usage: /cmreload
    aliases: [ cmrl ]
  cmconfig:
    description: config functions
    usage: /cmconfig [reload|query|set] [args...]
    aliases: [ cmcfg ]
  cmdata:
    description: data functions
    usage: /cmdata [query] [args...]
    aliases: [ cmd ]
  query-report:
    description: Query reports
    usage: /query-report
    aliases: [ qr ]
  rcon:
    description: rcon functions
    usage: /rcon ip:port psd command
  link:
    description: link account and qq
    usage: /link name qq
  chamomile:
    description: Chamomile functions
    usage: /chamomile [help|data|report|reload|query-report] [args...]
    aliases: [ cm ]