name: Chamomile
version: 1.0.4
main: fun.bm.Chamomile
description: Encoded by Blue Millennium
authors: [ SukaXD, Suisuroru ]

commands:
  kill:
    description: Kill entities
    usage: /kill <entities>
  ban:
    description: Ban a player
    usage: /ban <player> <reason>
  pardon:
    description: Unban a player
    usage: /pardon <player>
  chamomilehelp:
    description: Chamomile help
    usage: /chamomilehelp
    aliases: [ cmhelp ]
  report:
    description: Report a player
    usage: /report <player> <reason>
    aliases: [ cmrp ]
  cmreload:
    description: Reload config
    usage: /cmreload
    aliases: [ cmrl ]
  cmconfig:
    description: Config functions
    usage: /cmconfig [reload|query|set] [args...]
    aliases: [ cmcfg ]
  cmdata:
    description: Data functions
    usage: /cmdata [query] [args...]
    aliases: [ cmd ]
  query-report:
    description: Query reports
    usage: /query-report
    aliases: [ qr ]
  del-report:
    description: Delete reports
    usage: /del-report <timestamp>
    aliases: [ dr ]
  bind:
    description: Link account and qq
    usage: /bind name qq
  check:
    description: Verify or delete check data
    usage: /check [del|verify] [args...]
  chamomile:
    description: Chamomile functions
    usage: /chamomile [help|report|reload|config|data|check|kill|query-report|del-report] [args...]
    aliases: [ cm ]